#eureka:
#  instance:
#    appname: sender-statement
#    hostname: localhost

#server:
#  port: 7012

#spring:
#  kafka:
#    bootstrap-servers: 142.93.60.121:9092

#topic:
#  statement:
#    sender: sender4
#    update: update3
#    retry: retry3


server:
  port: 7012

spring:
  kafka:
    bootstrap-servers: localhost:9092

topic:
  statement:
    update: dev-updates2
    sender: dev-sender2
    retry: dev-retry1

